/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _HomeMenu_snd_popdown_h_
#define _HomeMenu_snd_popdown_h_
//---------------------------------------------------------------------------------
extern const unsigned char HomeMenu_snd_popdown[];
extern const int HomeMenu_snd_popdown_size;
//---------------------------------------------------------------------------------
#endif //_HomeMenu_snd_popdown_h_
//---------------------------------------------------------------------------------
