/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _HomeMenu_snd_ping_h_
#define _HomeMenu_snd_ping_h_
//---------------------------------------------------------------------------------
extern const unsigned char HomeMenu_snd_ping[];
extern const int HomeMenu_snd_ping_size;
//---------------------------------------------------------------------------------
#endif //_HomeMenu_snd_ping_h_
//---------------------------------------------------------------------------------
